//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public System.DateTime DateOrder { get; set; }
        public decimal Total { get; set; }
        public Nullable<double> Discount { get; set; }
        public string UserId { get; set; }
        public string Address { get; set; }
    }
}
