//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string Categories { get; set; }
        public string Language { get; set; }
        public string Image { get; set; }
    }
}
